/* This file generated by Tools/core_objects/gen_header.py */

#define unicode_object(len, txt...) \
    { \
    .ob_base = {         _PyObject_EXTRA_INIT \
        1000, \
        &PyUnicode_Type, \
    }, \
    .length = (len), \
    .hash = -1, \
    .state = { \
        .interned = SSTATE_NOT_INTERNED, \
        .kind = PyUnicode_1BYTE_KIND, \
        .compact = 1, \
        .ascii = 1, \
        .ready = 1, \
    }, \
    .wstr = NULL, \
    }, \
    .text = txt

#define init_unicode_object(name) \
    ref = (PyObject *)&_Py_id_strings.id_name, PyUnicode_InternInPlace(&ref), Py_DECREF(ref)


#include "core_objects.h"

_PyIdStrings _Py_id_strings = {
    .id___abc_tpflags__ = { unicode_object(15, { '_', '_', 'a', 'b', 'c', '_', 't', 'p', 'f', 'l', 'a', 'g', 's', '_', '_'}) },
    .id___abs__ = { unicode_object(7, { '_', '_', 'a', 'b', 's', '_', '_'}) },
    .id___abstractmethods__ = { unicode_object(19, { '_', '_', 'a', 'b', 's', 't', 'r', 'a', 'c', 't', 'm', 'e', 't', 'h', 'o', 'd', 's', '_', '_'}) },
    .id___adapt__ = { unicode_object(9, { '_', '_', 'a', 'd', 'a', 'p', 't', '_', '_'}) },
    .id___add__ = { unicode_object(7, { '_', '_', 'a', 'd', 'd', '_', '_'}) },
    .id___aenter__ = { unicode_object(10, { '_', '_', 'a', 'e', 'n', 't', 'e', 'r', '_', '_'}) },
    .id___aexit__ = { unicode_object(9, { '_', '_', 'a', 'e', 'x', 'i', 't', '_', '_'}) },
    .id___aiter__ = { unicode_object(9, { '_', '_', 'a', 'i', 't', 'e', 'r', '_', '_'}) },
    .id___all__ = { unicode_object(7, { '_', '_', 'a', 'l', 'l', '_', '_'}) },
    .id___and__ = { unicode_object(7, { '_', '_', 'a', 'n', 'd', '_', '_'}) },
    .id___anext__ = { unicode_object(9, { '_', '_', 'a', 'n', 'e', 'x', 't', '_', '_'}) },
    .id___annotations__ = { unicode_object(15, { '_', '_', 'a', 'n', 'n', 'o', 't', 'a', 't', 'i', 'o', 'n', 's', '_', '_'}) },
    .id___args__ = { unicode_object(8, { '_', '_', 'a', 'r', 'g', 's', '_', '_'}) },
    .id___asyncio_running_event_loop__ = { unicode_object(30, { '_', '_', 'a', 's', 'y', 'n', 'c', 'i', 'o', '_', 'r', 'u', 'n', 'n', 'i', 'n', 'g', '_', 'e', 'v', 'e', 'n', 't', '_', 'l', 'o', 'o', 'p', '_', '_'}) },
    .id___await__ = { unicode_object(9, { '_', '_', 'a', 'w', 'a', 'i', 't', '_', '_'}) },
    .id___bases__ = { unicode_object(9, { '_', '_', 'b', 'a', 's', 'e', 's', '_', '_'}) },
    .id___bool__ = { unicode_object(8, { '_', '_', 'b', 'o', 'o', 'l', '_', '_'}) },
    .id___build_class__ = { unicode_object(15, { '_', '_', 'b', 'u', 'i', 'l', 'd', '_', 'c', 'l', 'a', 's', 's', '_', '_'}) },
    .id___builtins__ = { unicode_object(12, { '_', '_', 'b', 'u', 'i', 'l', 't', 'i', 'n', 's', '_', '_'}) },
    .id___bytes__ = { unicode_object(9, { '_', '_', 'b', 'y', 't', 'e', 's', '_', '_'}) },
    .id___call__ = { unicode_object(8, { '_', '_', 'c', 'a', 'l', 'l', '_', '_'}) },
    .id___cantrace__ = { unicode_object(12, { '_', '_', 'c', 'a', 'n', 't', 'r', 'a', 'c', 'e', '_', '_'}) },
    .id___ceil__ = { unicode_object(8, { '_', '_', 'c', 'e', 'i', 'l', '_', '_'}) },
    .id___class__ = { unicode_object(9, { '_', '_', 'c', 'l', 'a', 's', 's', '_', '_'}) },
    .id___class_getitem__ = { unicode_object(17, { '_', '_', 'c', 'l', 'a', 's', 's', '_', 'g', 'e', 't', 'i', 't', 'e', 'm', '_', '_'}) },
    .id___classcell__ = { unicode_object(13, { '_', '_', 'c', 'l', 'a', 's', 's', 'c', 'e', 'l', 'l', '_', '_'}) },
    .id___complex__ = { unicode_object(11, { '_', '_', 'c', 'o', 'm', 'p', 'l', 'e', 'x', '_', '_'}) },
    .id___conform__ = { unicode_object(11, { '_', '_', 'c', 'o', 'n', 'f', 'o', 'r', 'm', '_', '_'}) },
    .id___contains__ = { unicode_object(12, { '_', '_', 'c', 'o', 'n', 't', 'a', 'i', 'n', 's', '_', '_'}) },
    .id___copy__ = { unicode_object(8, { '_', '_', 'c', 'o', 'p', 'y', '_', '_'}) },
    .id___ctypes_from_outparam__ = { unicode_object(24, { '_', '_', 'c', 't', 'y', 'p', 'e', 's', '_', 'f', 'r', 'o', 'm', '_', 'o', 'u', 't', 'p', 'a', 'r', 'a', 'm', '_', '_'}) },
    .id___del__ = { unicode_object(7, { '_', '_', 'd', 'e', 'l', '_', '_'}) },
    .id___delattr__ = { unicode_object(11, { '_', '_', 'd', 'e', 'l', 'a', 't', 't', 'r', '_', '_'}) },
    .id___delete__ = { unicode_object(10, { '_', '_', 'd', 'e', 'l', 'e', 't', 'e', '_', '_'}) },
    .id___delitem__ = { unicode_object(11, { '_', '_', 'd', 'e', 'l', 'i', 't', 'e', 'm', '_', '_'}) },
    .id___dict__ = { unicode_object(8, { '_', '_', 'd', 'i', 'c', 't', '_', '_'}) },
    .id___dir__ = { unicode_object(7, { '_', '_', 'd', 'i', 'r', '_', '_'}) },
    .id___divmod__ = { unicode_object(10, { '_', '_', 'd', 'i', 'v', 'm', 'o', 'd', '_', '_'}) },
    .id___doc__ = { unicode_object(7, { '_', '_', 'd', 'o', 'c', '_', '_'}) },
    .id___enter__ = { unicode_object(9, { '_', '_', 'e', 'n', 't', 'e', 'r', '_', '_'}) },
    .id___eq__ = { unicode_object(6, { '_', '_', 'e', 'q', '_', '_'}) },
    .id___exit__ = { unicode_object(8, { '_', '_', 'e', 'x', 'i', 't', '_', '_'}) },
    .id___file__ = { unicode_object(8, { '_', '_', 'f', 'i', 'l', 'e', '_', '_'}) },
    .id___floor__ = { unicode_object(9, { '_', '_', 'f', 'l', 'o', 'o', 'r', '_', '_'}) },
    .id___floordiv__ = { unicode_object(12, { '_', '_', 'f', 'l', 'o', 'o', 'r', 'd', 'i', 'v', '_', '_'}) },
    .id___float__ = { unicode_object(9, { '_', '_', 'f', 'l', 'o', 'a', 't', '_', '_'}) },
    .id___format__ = { unicode_object(10, { '_', '_', 'f', 'o', 'r', 'm', 'a', 't', '_', '_'}) },
    .id___fspath__ = { unicode_object(10, { '_', '_', 'f', 's', 'p', 'a', 't', 'h', '_', '_'}) },
    .id___ge__ = { unicode_object(6, { '_', '_', 'g', 'e', '_', '_'}) },
    .id___get__ = { unicode_object(7, { '_', '_', 'g', 'e', 't', '_', '_'}) },
    .id___getattr__ = { unicode_object(11, { '_', '_', 'g', 'e', 't', 'a', 't', 't', 'r', '_', '_'}) },
    .id___getattribute__ = { unicode_object(16, { '_', '_', 'g', 'e', 't', 'a', 't', 't', 'r', 'i', 'b', 'u', 't', 'e', '_', '_'}) },
    .id___getinitargs__ = { unicode_object(15, { '_', '_', 'g', 'e', 't', 'i', 'n', 'i', 't', 'a', 'r', 'g', 's', '_', '_'}) },
    .id___getitem__ = { unicode_object(11, { '_', '_', 'g', 'e', 't', 'i', 't', 'e', 'm', '_', '_'}) },
    .id___getnewargs__ = { unicode_object(14, { '_', '_', 'g', 'e', 't', 'n', 'e', 'w', 'a', 'r', 'g', 's', '_', '_'}) },
    .id___getnewargs_ex__ = { unicode_object(17, { '_', '_', 'g', 'e', 't', 'n', 'e', 'w', 'a', 'r', 'g', 's', '_', 'e', 'x', '_', '_'}) },
    .id___getstate__ = { unicode_object(12, { '_', '_', 'g', 'e', 't', 's', 't', 'a', 't', 'e', '_', '_'}) },
    .id___gt__ = { unicode_object(6, { '_', '_', 'g', 't', '_', '_'}) },
    .id___hash__ = { unicode_object(8, { '_', '_', 'h', 'a', 's', 'h', '_', '_'}) },
    .id___iadd__ = { unicode_object(8, { '_', '_', 'i', 'a', 'd', 'd', '_', '_'}) },
    .id___iand__ = { unicode_object(8, { '_', '_', 'i', 'a', 'n', 'd', '_', '_'}) },
    .id___ifloordiv__ = { unicode_object(13, { '_', '_', 'i', 'f', 'l', 'o', 'o', 'r', 'd', 'i', 'v', '_', '_'}) },
    .id___ilshift__ = { unicode_object(11, { '_', '_', 'i', 'l', 's', 'h', 'i', 'f', 't', '_', '_'}) },
    .id___import__ = { unicode_object(10, { '_', '_', 'i', 'm', 'p', 'o', 'r', 't', '_', '_'}) },
    .id___imatmul__ = { unicode_object(11, { '_', '_', 'i', 'm', 'a', 't', 'm', 'u', 'l', '_', '_'}) },
    .id___imod__ = { unicode_object(8, { '_', '_', 'i', 'm', 'o', 'd', '_', '_'}) },
    .id___imul__ = { unicode_object(8, { '_', '_', 'i', 'm', 'u', 'l', '_', '_'}) },
    .id___index__ = { unicode_object(9, { '_', '_', 'i', 'n', 'd', 'e', 'x', '_', '_'}) },
    .id___init__ = { unicode_object(8, { '_', '_', 'i', 'n', 'i', 't', '_', '_'}) },
    .id___init_subclass__ = { unicode_object(17, { '_', '_', 'i', 'n', 'i', 't', '_', 's', 'u', 'b', 'c', 'l', 'a', 's', 's', '_', '_'}) },
    .id___instancecheck__ = { unicode_object(17, { '_', '_', 'i', 'n', 's', 't', 'a', 'n', 'c', 'e', 'c', 'h', 'e', 'c', 'k', '_', '_'}) },
    .id___int__ = { unicode_object(7, { '_', '_', 'i', 'n', 't', '_', '_'}) },
    .id___invert__ = { unicode_object(10, { '_', '_', 'i', 'n', 'v', 'e', 'r', 't', '_', '_'}) },
    .id___ior__ = { unicode_object(7, { '_', '_', 'i', 'o', 'r', '_', '_'}) },
    .id___ipow__ = { unicode_object(8, { '_', '_', 'i', 'p', 'o', 'w', '_', '_'}) },
    .id___irshift__ = { unicode_object(11, { '_', '_', 'i', 'r', 's', 'h', 'i', 'f', 't', '_', '_'}) },
    .id___isabstractmethod__ = { unicode_object(20, { '_', '_', 'i', 's', 'a', 'b', 's', 't', 'r', 'a', 'c', 't', 'm', 'e', 't', 'h', 'o', 'd', '_', '_'}) },
    .id___isub__ = { unicode_object(8, { '_', '_', 'i', 's', 'u', 'b', '_', '_'}) },
    .id___iter__ = { unicode_object(8, { '_', '_', 'i', 't', 'e', 'r', '_', '_'}) },
    .id___itruediv__ = { unicode_object(12, { '_', '_', 'i', 't', 'r', 'u', 'e', 'd', 'i', 'v', '_', '_'}) },
    .id___ixor__ = { unicode_object(8, { '_', '_', 'i', 'x', 'o', 'r', '_', '_'}) },
    .id___le__ = { unicode_object(6, { '_', '_', 'l', 'e', '_', '_'}) },
    .id___len__ = { unicode_object(7, { '_', '_', 'l', 'e', 'n', '_', '_'}) },
    .id___length_hint__ = { unicode_object(15, { '_', '_', 'l', 'e', 'n', 'g', 't', 'h', '_', 'h', 'i', 'n', 't', '_', '_'}) },
    .id___loader__ = { unicode_object(10, { '_', '_', 'l', 'o', 'a', 'd', 'e', 'r', '_', '_'}) },
    .id___lshift__ = { unicode_object(10, { '_', '_', 'l', 's', 'h', 'i', 'f', 't', '_', '_'}) },
    .id___ltrace__ = { unicode_object(10, { '_', '_', 'l', 't', 'r', 'a', 'c', 'e', '_', '_'}) },
    .id___lt__ = { unicode_object(6, { '_', '_', 'l', 't', '_', '_'}) },
    .id___main__ = { unicode_object(8, { '_', '_', 'm', 'a', 'i', 'n', '_', '_'}) },
    .id___matmul__ = { unicode_object(10, { '_', '_', 'm', 'a', 't', 'm', 'u', 'l', '_', '_'}) },
    .id___missing__ = { unicode_object(11, { '_', '_', 'm', 'i', 's', 's', 'i', 'n', 'g', '_', '_'}) },
    .id___mod__ = { unicode_object(7, { '_', '_', 'm', 'o', 'd', '_', '_'}) },
    .id___module__ = { unicode_object(10, { '_', '_', 'm', 'o', 'd', 'u', 'l', 'e', '_', '_'}) },
    .id___mro_entries__ = { unicode_object(15, { '_', '_', 'm', 'r', 'o', '_', 'e', 'n', 't', 'r', 'i', 'e', 's', '_', '_'}) },
    .id___mul__ = { unicode_object(7, { '_', '_', 'm', 'u', 'l', '_', '_'}) },
    .id___name__ = { unicode_object(8, { '_', '_', 'n', 'a', 'm', 'e', '_', '_'}) },
    .id___ne__ = { unicode_object(6, { '_', '_', 'n', 'e', '_', '_'}) },
    .id___neg__ = { unicode_object(7, { '_', '_', 'n', 'e', 'g', '_', '_'}) },
    .id___new__ = { unicode_object(7, { '_', '_', 'n', 'e', 'w', '_', '_'}) },
    .id___newobj__ = { unicode_object(10, { '_', '_', 'n', 'e', 'w', 'o', 'b', 'j', '_', '_'}) },
    .id___newobj_ex__ = { unicode_object(13, { '_', '_', 'n', 'e', 'w', 'o', 'b', 'j', '_', 'e', 'x', '_', '_'}) },
    .id___next__ = { unicode_object(8, { '_', '_', 'n', 'e', 'x', 't', '_', '_'}) },
    .id___or__ = { unicode_object(6, { '_', '_', 'o', 'r', '_', '_'}) },
    .id___origin__ = { unicode_object(10, { '_', '_', 'o', 'r', 'i', 'g', 'i', 'n', '_', '_'}) },
    .id___package__ = { unicode_object(11, { '_', '_', 'p', 'a', 'c', 'k', 'a', 'g', 'e', '_', '_'}) },
    .id___parameters__ = { unicode_object(14, { '_', '_', 'p', 'a', 'r', 'a', 'm', 'e', 't', 'e', 'r', 's', '_', '_'}) },
    .id___path__ = { unicode_object(8, { '_', '_', 'p', 'a', 't', 'h', '_', '_'}) },
    .id___pos__ = { unicode_object(7, { '_', '_', 'p', 'o', 's', '_', '_'}) },
    .id___pow__ = { unicode_object(7, { '_', '_', 'p', 'o', 'w', '_', '_'}) },
    .id___prepare__ = { unicode_object(11, { '_', '_', 'p', 'r', 'e', 'p', 'a', 'r', 'e', '_', '_'}) },
    .id___qualname__ = { unicode_object(12, { '_', '_', 'q', 'u', 'a', 'l', 'n', 'a', 'm', 'e', '_', '_'}) },
    .id___radd__ = { unicode_object(8, { '_', '_', 'r', 'a', 'd', 'd', '_', '_'}) },
    .id___rand__ = { unicode_object(8, { '_', '_', 'r', 'a', 'n', 'd', '_', '_'}) },
    .id___rdivmod__ = { unicode_object(11, { '_', '_', 'r', 'd', 'i', 'v', 'm', 'o', 'd', '_', '_'}) },
    .id___reduce__ = { unicode_object(10, { '_', '_', 'r', 'e', 'd', 'u', 'c', 'e', '_', '_'}) },
    .id___reduce_ex__ = { unicode_object(13, { '_', '_', 'r', 'e', 'd', 'u', 'c', 'e', '_', 'e', 'x', '_', '_'}) },
    .id___repr__ = { unicode_object(8, { '_', '_', 'r', 'e', 'p', 'r', '_', '_'}) },
    .id___reversed__ = { unicode_object(12, { '_', '_', 'r', 'e', 'v', 'e', 'r', 's', 'e', 'd', '_', '_'}) },
    .id___rfloordiv__ = { unicode_object(13, { '_', '_', 'r', 'f', 'l', 'o', 'o', 'r', 'd', 'i', 'v', '_', '_'}) },
    .id___rlshift__ = { unicode_object(11, { '_', '_', 'r', 'l', 's', 'h', 'i', 'f', 't', '_', '_'}) },
    .id___rmatmul__ = { unicode_object(11, { '_', '_', 'r', 'm', 'a', 't', 'm', 'u', 'l', '_', '_'}) },
    .id___rmod__ = { unicode_object(8, { '_', '_', 'r', 'm', 'o', 'd', '_', '_'}) },
    .id___rmul__ = { unicode_object(8, { '_', '_', 'r', 'm', 'u', 'l', '_', '_'}) },
    .id___ror__ = { unicode_object(7, { '_', '_', 'r', 'o', 'r', '_', '_'}) },
    .id___round__ = { unicode_object(9, { '_', '_', 'r', 'o', 'u', 'n', 'd', '_', '_'}) },
    .id___rpow__ = { unicode_object(8, { '_', '_', 'r', 'p', 'o', 'w', '_', '_'}) },
    .id___rrshift__ = { unicode_object(11, { '_', '_', 'r', 'r', 's', 'h', 'i', 'f', 't', '_', '_'}) },
    .id___rshift__ = { unicode_object(10, { '_', '_', 'r', 's', 'h', 'i', 'f', 't', '_', '_'}) },
    .id___rsub__ = { unicode_object(8, { '_', '_', 'r', 's', 'u', 'b', '_', '_'}) },
    .id___rtruediv__ = { unicode_object(12, { '_', '_', 'r', 't', 'r', 'u', 'e', 'd', 'i', 'v', '_', '_'}) },
    .id___rxor__ = { unicode_object(8, { '_', '_', 'r', 'x', 'o', 'r', '_', '_'}) },
    .id___set__ = { unicode_object(7, { '_', '_', 's', 'e', 't', '_', '_'}) },
    .id___set_name__ = { unicode_object(12, { '_', '_', 's', 'e', 't', '_', 'n', 'a', 'm', 'e', '_', '_'}) },
    .id___setattr__ = { unicode_object(11, { '_', '_', 's', 'e', 't', 'a', 't', 't', 'r', '_', '_'}) },
    .id___setitem__ = { unicode_object(11, { '_', '_', 's', 'e', 't', 'i', 't', 'e', 'm', '_', '_'}) },
    .id___setstate__ = { unicode_object(12, { '_', '_', 's', 'e', 't', 's', 't', 'a', 't', 'e', '_', '_'}) },
    .id___sizeof__ = { unicode_object(10, { '_', '_', 's', 'i', 'z', 'e', 'o', 'f', '_', '_'}) },
    .id___slotnames__ = { unicode_object(13, { '_', '_', 's', 'l', 'o', 't', 'n', 'a', 'm', 'e', 's', '_', '_'}) },
    .id___slots__ = { unicode_object(9, { '_', '_', 's', 'l', 'o', 't', 's', '_', '_'}) },
    .id___spec__ = { unicode_object(8, { '_', '_', 's', 'p', 'e', 'c', '_', '_'}) },
    .id___str__ = { unicode_object(7, { '_', '_', 's', 't', 'r', '_', '_'}) },
    .id___sub__ = { unicode_object(7, { '_', '_', 's', 'u', 'b', '_', '_'}) },
    .id___subclasscheck__ = { unicode_object(17, { '_', '_', 's', 'u', 'b', 'c', 'l', 'a', 's', 's', 'c', 'h', 'e', 'c', 'k', '_', '_'}) },
    .id___subclasshook__ = { unicode_object(16, { '_', '_', 's', 'u', 'b', 'c', 'l', 'a', 's', 's', 'h', 'o', 'o', 'k', '_', '_'}) },
    .id___tp_del__ = { unicode_object(10, { '_', '_', 't', 'p', '_', 'd', 'e', 'l', '_', '_'}) },
    .id___truediv__ = { unicode_object(11, { '_', '_', 't', 'r', 'u', 'e', 'd', 'i', 'v', '_', '_'}) },
    .id___trunc__ = { unicode_object(9, { '_', '_', 't', 'r', 'u', 'n', 'c', '_', '_'}) },
    .id___warningregistry__ = { unicode_object(19, { '_', '_', 'w', 'a', 'r', 'n', 'i', 'n', 'g', 'r', 'e', 'g', 'i', 's', 't', 'r', 'y', '_', '_'}) },
    .id___weakref__ = { unicode_object(11, { '_', '_', 'w', 'e', 'a', 'k', 'r', 'e', 'f', '_', '_'}) },
    .id___xor__ = { unicode_object(7, { '_', '_', 'x', 'o', 'r', '_', '_'}) },
    .id__ = { unicode_object(1, { '_'}) },
    .id___IOBase_closed = { unicode_object(15, { '_', '_', 'I', 'O', 'B', 'a', 's', 'e', '_', 'c', 'l', 'o', 's', 'e', 'd'}) },
    .id__abc_impl = { unicode_object(9, { '_', 'a', 'b', 'c', '_', 'i', 'm', 'p', 'l'}) },
    .id__abstract_ = { unicode_object(10, { '_', 'a', 'b', 's', 't', 'r', 'a', 'c', 't', '_'}) },
    .id__anonymous_ = { unicode_object(11, { '_', 'a', 'n', 'o', 'n', 'y', 'm', 'o', 'u', 's', '_'}) },
    .id__argtypes_ = { unicode_object(10, { '_', 'a', 'r', 'g', 't', 'y', 'p', 'e', 's', '_'}) },
    .id__array_reconstructor = { unicode_object(20, { '_', 'a', 'r', 'r', 'a', 'y', '_', 'r', 'e', 'c', 'o', 'n', 's', 't', 'r', 'u', 'c', 't', 'o', 'r'}) },
    .id__as_parameter_ = { unicode_object(14, { '_', 'a', 's', '_', 'p', 'a', 'r', 'a', 'm', 'e', 't', 'e', 'r', '_'}) },
    .id__asyncio_future_blocking = { unicode_object(24, { '_', 'a', 's', 'y', 'n', 'c', 'i', 'o', '_', 'f', 'u', 't', 'u', 'r', 'e', '_', 'b', 'l', 'o', 'c', 'k', 'i', 'n', 'g'}) },
    .id__blksize = { unicode_object(8, { '_', 'b', 'l', 'k', 's', 'i', 'z', 'e'}) },
    .id__check_retval_ = { unicode_object(14, { '_', 'c', 'h', 'e', 'c', 'k', '_', 'r', 'e', 't', 'v', 'a', 'l', '_'}) },
    .id__dealloc_warn = { unicode_object(13, { '_', 'd', 'e', 'a', 'l', 'l', 'o', 'c', '_', 'w', 'a', 'r', 'n'}) },
    .id__fields_ = { unicode_object(8, { '_', 'f', 'i', 'e', 'l', 'd', 's', '_'}) },
    .id__finalizing = { unicode_object(11, { '_', 'f', 'i', 'n', 'a', 'l', 'i', 'z', 'i', 'n', 'g'}) },
    .id__find_and_load = { unicode_object(14, { '_', 'f', 'i', 'n', 'd', '_', 'a', 'n', 'd', '_', 'l', 'o', 'a', 'd'}) },
    .id__fix_up_module = { unicode_object(14, { '_', 'f', 'i', 'x', '_', 'u', 'p', '_', 'm', 'o', 'd', 'u', 'l', 'e'}) },
    .id__flags_ = { unicode_object(7, { '_', 'f', 'l', 'a', 'g', 's', '_'}) },
    .id__get_sourcefile = { unicode_object(15, { '_', 'g', 'e', 't', '_', 's', 'o', 'u', 'r', 'c', 'e', 'f', 'i', 'l', 'e'}) },
    .id__handle_fromlist = { unicode_object(16, { '_', 'h', 'a', 'n', 'd', 'l', 'e', '_', 'f', 'r', 'o', 'm', 'l', 'i', 's', 't'}) },
    .id__initializing = { unicode_object(13, { '_', 'i', 'n', 'i', 't', 'i', 'a', 'l', 'i', 'z', 'i', 'n', 'g'}) },
    .id__is_text_encoding = { unicode_object(17, { '_', 'i', 's', '_', 't', 'e', 'x', 't', '_', 'e', 'n', 'c', 'o', 'd', 'i', 'n', 'g'}) },
    .id__iterdump = { unicode_object(9, { '_', 'i', 't', 'e', 'r', 'd', 'u', 'm', 'p'}) },
    .id__length_ = { unicode_object(8, { '_', 'l', 'e', 'n', 'g', 't', 'h', '_'}) },
    .id__lock_unlock_module = { unicode_object(19, { '_', 'l', 'o', 'c', 'k', '_', 'u', 'n', 'l', 'o', 'c', 'k', '_', 'm', 'o', 'd', 'u', 'l', 'e'}) },
    .id__loop = { unicode_object(5, { '_', 'l', 'o', 'o', 'p'}) },
    .id__needs_com_addref_ = { unicode_object(18, { '_', 'n', 'e', 'e', 'd', 's', '_', 'c', 'o', 'm', '_', 'a', 'd', 'd', 'r', 'e', 'f', '_'}) },
    .id__pack_ = { unicode_object(6, { '_', 'p', 'a', 'c', 'k', '_'}) },
    .id__repr_info = { unicode_object(10, { '_', 'r', 'e', 'p', 'r', '_', 'i', 'n', 'f', 'o'}) },
    .id__restype_ = { unicode_object(9, { '_', 'r', 'e', 's', 't', 'y', 'p', 'e', '_'}) },
    .id__showwarnmsg = { unicode_object(12, { '_', 's', 'h', 'o', 'w', 'w', 'a', 'r', 'n', 'm', 's', 'g'}) },
    .id__shutdown = { unicode_object(9, { '_', 's', 'h', 'u', 't', 'd', 'o', 'w', 'n'}) },
    .id__slotnames = { unicode_object(10, { '_', 's', 'l', 'o', 't', 'n', 'a', 'm', 'e', 's'}) },
    .id__strptime_datetime = { unicode_object(18, { '_', 's', 't', 'r', 'p', 't', 'i', 'm', 'e', '_', 'd', 'a', 't', 'e', 't', 'i', 'm', 'e'}) },
    .id__strptime_time = { unicode_object(14, { '_', 's', 't', 'r', 'p', 't', 'i', 'm', 'e', '_', 't', 'i', 'm', 'e'}) },
    .id__swappedbytes_ = { unicode_object(14, { '_', 's', 'w', 'a', 'p', 'p', 'e', 'd', 'b', 'y', 't', 'e', 's', '_'}) },
    .id__type_ = { unicode_object(6, { '_', 't', 'y', 'p', 'e', '_'}) },
    .id__uninitialized_submodules = { unicode_object(25, { '_', 'u', 'n', 'i', 'n', 'i', 't', 'i', 'a', 'l', 'i', 'z', 'e', 'd', '_', 's', 'u', 'b', 'm', 'o', 'd', 'u', 'l', 'e', 's'}) },
    .id__use_broken_old_ctypes_structure_semantics_ = { unicode_object(43, { '_', 'u', 's', 'e', '_', 'b', 'r', 'o', 'k', 'e', 'n', '_', 'o', 'l', 'd', '_', 'c', 't', 'y', 'p', 'e', 's', '_', 's', 't', 'r', 'u', 'c', 't', 'u', 'r', 'e', '_', 's', 'e', 'm', 'a', 'n', 't', 'i', 'c', 's', '_'}) },
    .id__warn_unawaited_coroutine = { unicode_object(25, { '_', 'w', 'a', 'r', 'n', '_', 'u', 'n', 'a', 'w', 'a', 'i', 't', 'e', 'd', '_', 'c', 'o', 'r', 'o', 'u', 't', 'i', 'n', 'e'}) },
    .id__xoptions = { unicode_object(9, { '_', 'x', 'o', 'p', 't', 'i', 'o', 'n', 's'}) },
    .id_add = { unicode_object(3, { 'a', 'd', 'd'}) },
    .id_add_done_callback = { unicode_object(17, { 'a', 'd', 'd', '_', 'd', 'o', 'n', 'e', '_', 'c', 'a', 'l', 'l', 'b', 'a', 'c', 'k'}) },
    .id_append = { unicode_object(6, { 'a', 'p', 'p', 'e', 'n', 'd'}) },
    .id_as_integer_ratio = { unicode_object(16, { 'a', 's', '_', 'i', 'n', 't', 'e', 'g', 'e', 'r', '_', 'r', 'a', 't', 'i', 'o'}) },
    .id_big = { unicode_object(3, { 'b', 'i', 'g'}) },
    .id_buffer = { unicode_object(6, { 'b', 'u', 'f', 'f', 'e', 'r'}) },
    .id_builtins = { unicode_object(8, { 'b', 'u', 'i', 'l', 't', 'i', 'n', 's'}) },
    .id_call_exception_handler = { unicode_object(22, { 'c', 'a', 'l', 'l', '_', 'e', 'x', 'c', 'e', 'p', 't', 'i', 'o', 'n', '_', 'h', 'a', 'n', 'd', 'l', 'e', 'r'}) },
    .id_call_soon = { unicode_object(9, { 'c', 'a', 'l', 'l', '_', 's', 'o', 'o', 'n'}) },
    .id_cancel = { unicode_object(6, { 'c', 'a', 'n', 'c', 'e', 'l'}) },
    .id_clear = { unicode_object(5, { 'c', 'l', 'e', 'a', 'r'}) },
    .id_close = { unicode_object(5, { 'c', 'l', 'o', 's', 'e'}) },
    .id_code = { unicode_object(4, { 'c', 'o', 'd', 'e'}) },
    .id_copy = { unicode_object(4, { 'c', 'o', 'p', 'y'}) },
    .id_copyreg = { unicode_object(7, { 'c', 'o', 'p', 'y', 'r', 'e', 'g'}) },
    .id_cursor = { unicode_object(6, { 'c', 'u', 'r', 's', 'o', 'r'}) },
    .id_decode = { unicode_object(6, { 'd', 'e', 'c', 'o', 'd', 'e'}) },
    .id_default = { unicode_object(7, { 'd', 'e', 'f', 'a', 'u', 'l', 't'}) },
    .id_defaultaction = { unicode_object(13, { 'd', 'e', 'f', 'a', 'u', 'l', 't', 'a', 'c', 't', 'i', 'o', 'n'}) },
    .id_dict_size = { unicode_object(9, { 'd', 'i', 'c', 't', '_', 's', 'i', 'z', 'e'}) },
    .id_difference_update = { unicode_object(17, { 'd', 'i', 'f', 'f', 'e', 'r', 'e', 'n', 'c', 'e', '_', 'u', 'p', 'd', 'a', 't', 'e'}) },
    .id_discard = { unicode_object(7, { 'd', 'i', 's', 'c', 'a', 'r', 'd'}) },
    .id_dispatch_table = { unicode_object(14, { 'd', 'i', 's', 'p', 'a', 't', 'c', 'h', '_', 't', 'a', 'b', 'l', 'e'}) },
    .id_displayhook = { unicode_object(11, { 'd', 'i', 's', 'p', 'l', 'a', 'y', 'h', 'o', 'o', 'k'}) },
    .id_dist = { unicode_object(4, { 'd', 'i', 's', 't'}) },
    .id_doctype = { unicode_object(7, { 'd', 'o', 'c', 't', 'y', 'p', 'e'}) },
    .id_enable = { unicode_object(6, { 'e', 'n', 'a', 'b', 'l', 'e'}) },
    .id_encoding = { unicode_object(8, { 'e', 'n', 'c', 'o', 'd', 'i', 'n', 'g'}) },
    .id_end_lineno = { unicode_object(10, { 'e', 'n', 'd', '_', 'l', 'i', 'n', 'e', 'n', 'o'}) },
    .id_end_offset = { unicode_object(10, { 'e', 'n', 'd', '_', 'o', 'f', 'f', 's', 'e', 't'}) },
    .id_errors = { unicode_object(6, { 'e', 'r', 'r', 'o', 'r', 's'}) },
    .id_excepthook = { unicode_object(10, { 'e', 'x', 'c', 'e', 'p', 't', 'h', 'o', 'o', 'k'}) },
    .id_exception = { unicode_object(9, { 'e', 'x', 'c', 'e', 'p', 't', 'i', 'o', 'n'}) },
    .id_execute = { unicode_object(7, { 'e', 'x', 'e', 'c', 'u', 't', 'e'}) },
    .id_executemany = { unicode_object(11, { 'e', 'x', 'e', 'c', 'u', 't', 'e', 'm', 'a', 'n', 'y'}) },
    .id_executescript = { unicode_object(13, { 'e', 'x', 'e', 'c', 'u', 't', 'e', 's', 'c', 'r', 'i', 'p', 't'}) },
    .id_extend = { unicode_object(6, { 'e', 'x', 't', 'e', 'n', 'd'}) },
    .id_false = { unicode_object(5, { 'f', 'a', 'l', 's', 'e'}) },
    .id_filename = { unicode_object(8, { 'f', 'i', 'l', 'e', 'n', 'a', 'm', 'e'}) },
    .id_fileno = { unicode_object(6, { 'f', 'i', 'l', 'e', 'n', 'o'}) },
    .id_fillvalue = { unicode_object(9, { 'f', 'i', 'l', 'l', 'v', 'a', 'l', 'u', 'e'}) },
    .id_filters = { unicode_object(7, { 'f', 'i', 'l', 't', 'e', 'r', 's'}) },
    .id_finalize = { unicode_object(8, { 'f', 'i', 'n', 'a', 'l', 'i', 'z', 'e'}) },
    .id_find = { unicode_object(4, { 'f', 'i', 'n', 'd'}) },
    .id_find_class = { unicode_object(10, { 'f', 'i', 'n', 'd', '_', 'c', 'l', 'a', 's', 's'}) },
    .id_findall = { unicode_object(7, { 'f', 'i', 'n', 'd', 'a', 'l', 'l'}) },
    .id_findtext = { unicode_object(8, { 'f', 'i', 'n', 'd', 't', 'e', 'x', 't'}) },
    .id_flush = { unicode_object(5, { 'f', 'l', 'u', 's', 'h'}) },
    .id_foo = { unicode_object(3, { 'f', 'o', 'o'}) },
    .id_from_param = { unicode_object(10, { 'f', 'r', 'o', 'm', '_', 'p', 'a', 'r', 'a', 'm'}) },
    .id_fromtimestamp = { unicode_object(13, { 'f', 'r', 'o', 'm', 't', 'i', 'm', 'e', 's', 't', 'a', 'm', 'p'}) },
    .id_fromutc = { unicode_object(7, { 'f', 'r', 'o', 'm', 'u', 't', 'c'}) },
    .id_future = { unicode_object(6, { 'f', 'u', 't', 'u', 'r', 'e'}) },
    .id_get = { unicode_object(3, { 'g', 'e', 't'}) },
    .id_get_debug = { unicode_object(9, { 'g', 'e', 't', '_', 'd', 'e', 'b', 'u', 'g'}) },
    .id_get_event_loop = { unicode_object(14, { 'g', 'e', 't', '_', 'e', 'v', 'e', 'n', 't', '_', 'l', 'o', 'o', 'p'}) },
    .id_get_loop = { unicode_object(8, { 'g', 'e', 't', '_', 'l', 'o', 'o', 'p'}) },
    .id_get_source = { unicode_object(10, { 'g', 'e', 't', '_', 's', 'o', 'u', 'r', 'c', 'e'}) },
    .id_getattr = { unicode_object(7, { 'g', 'e', 't', 'a', 't', 't', 'r'}) },
    .id_getnextcabinet = { unicode_object(14, { 'g', 'e', 't', 'n', 'e', 'x', 't', 'c', 'a', 'b', 'i', 'n', 'e', 't'}) },
    .id_id = { unicode_object(2, { 'i', 'd'}) },
    .id_ignore = { unicode_object(6, { 'i', 'g', 'n', 'o', 'r', 'e'}) },
    .id_importlib = { unicode_object(9, { 'i', 'm', 'p', 'o', 'r', 't', 'l', 'i', 'b'}) },
    .id_insert = { unicode_object(6, { 'i', 'n', 's', 'e', 'r', 't'}) },
    .id_intersection = { unicode_object(12, { 'i', 'n', 't', 'e', 'r', 's', 'e', 'c', 't', 'i', 'o', 'n'}) },
    .id_isatty = { unicode_object(6, { 'i', 's', 'a', 't', 't', 'y'}) },
    .id_isoformat = { unicode_object(9, { 'i', 's', 'o', 'f', 'o', 'r', 'm', 'a', 't'}) },
    .id_items = { unicode_object(5, { 'i', 't', 'e', 'm', 's'}) },
    .id_iter = { unicode_object(4, { 'i', 't', 'e', 'r'}) },
    .id_iterfind = { unicode_object(8, { 'i', 't', 'e', 'r', 'f', 'i', 'n', 'd'}) },
    .id_keys = { unicode_object(4, { 'k', 'e', 'y', 's'}) },
    .id_last_traceback = { unicode_object(14, { 'l', 'a', 's', 't', '_', 't', 'r', 'a', 'c', 'e', 'b', 'a', 'c', 'k'}) },
    .id_last_type = { unicode_object(9, { 'l', 'a', 's', 't', '_', 't', 'y', 'p', 'e'}) },
    .id_last_value = { unicode_object(10, { 'l', 'a', 's', 't', '_', 'v', 'a', 'l', 'u', 'e'}) },
    .id_latin1 = { unicode_object(6, { 'l', 'a', 't', 'i', 'n', '1'}) },
    .id_lc = { unicode_object(2, { 'l', 'c'}) },
    .id_lp = { unicode_object(2, { 'l', 'p'}) },
    .id_library = { unicode_object(7, { 'l', 'i', 'b', 'r', 'a', 'r', 'y'}) },
    .id_lineno = { unicode_object(6, { 'l', 'i', 'n', 'e', 'n', 'o'}) },
    .id_little = { unicode_object(6, { 'l', 'i', 't', 't', 'l', 'e'}) },
    .id_match = { unicode_object(5, { 'm', 'a', 't', 'c', 'h'}) },
    .id_message = { unicode_object(7, { 'm', 'e', 's', 's', 'a', 'g', 'e'}) },
    .id_metaclass = { unicode_object(9, { 'm', 'e', 't', 'a', 'c', 'l', 'a', 's', 's'}) },
    .id_mode = { unicode_object(4, { 'm', 'o', 'd', 'e'}) },
    .id_modules = { unicode_object(7, { 'm', 'o', 'd', 'u', 'l', 'e', 's'}) },
    .id_mro = { unicode_object(3, { 'm', 'r', 'o'}) },
    .id_msg = { unicode_object(3, { 'm', 's', 'g'}) },
    .id_n_fields = { unicode_object(8, { 'n', '_', 'f', 'i', 'e', 'l', 'd', 's'}) },
    .id_n_sequence_fields = { unicode_object(17, { 'n', '_', 's', 'e', 'q', 'u', 'e', 'n', 'c', 'e', '_', 'f', 'i', 'e', 'l', 'd', 's'}) },
    .id_n_unnamed_fields = { unicode_object(16, { 'n', '_', 'u', 'n', 'n', 'a', 'm', 'e', 'd', '_', 'f', 'i', 'e', 'l', 'd', 's'}) },
    .id_name = { unicode_object(4, { 'n', 'a', 'm', 'e'}) },
    .id_null = { unicode_object(4, { 'n', 'u', 'l', 'l'}) },
    .id_obj = { unicode_object(3, { 'o', 'b', 'j'}) },
    .id_offset = { unicode_object(6, { 'o', 'f', 'f', 's', 'e', 't'}) },
    .id_onceregistry = { unicode_object(12, { 'o', 'n', 'c', 'e', 'r', 'e', 'g', 'i', 's', 't', 'r', 'y'}) },
    .id_open = { unicode_object(4, { 'o', 'p', 'e', 'n'}) },
    .id_parent = { unicode_object(6, { 'p', 'a', 'r', 'e', 'n', 't'}) },
    .id_partial = { unicode_object(7, { 'p', 'a', 'r', 't', 'i', 'a', 'l'}) },
    .id_path = { unicode_object(4, { 'p', 'a', 't', 'h'}) },
    .id_pb = { unicode_object(2, { 'p', 'b'}) },
    .id_peek = { unicode_object(4, { 'p', 'e', 'e', 'k'}) },
    .id_persistent_id = { unicode_object(13, { 'p', 'e', 'r', 's', 'i', 's', 't', 'e', 'n', 't', '_', 'i', 'd'}) },
    .id_persistent_load = { unicode_object(15, { 'p', 'e', 'r', 's', 'i', 's', 't', 'e', 'n', 't', '_', 'l', 'o', 'a', 'd'}) },
    .id_print_file_and_line = { unicode_object(19, { 'p', 'r', 'i', 'n', 't', '_', 'f', 'i', 'l', 'e', '_', 'a', 'n', 'd', '_', 'l', 'i', 'n', 'e'}) },
    .id_ps1 = { unicode_object(3, { 'p', 's', '1'}) },
    .id_ps2 = { unicode_object(3, { 'p', 's', '2'}) },
    .id_raw = { unicode_object(3, { 'r', 'a', 'w'}) },
    .id_read = { unicode_object(4, { 'r', 'e', 'a', 'd'}) },
    .id_read1 = { unicode_object(5, { 'r', 'e', 'a', 'd', '1'}) },
    .id_readable = { unicode_object(8, { 'r', 'e', 'a', 'd', 'a', 'b', 'l', 'e'}) },
    .id_readall = { unicode_object(7, { 'r', 'e', 'a', 'd', 'a', 'l', 'l'}) },
    .id_readinto = { unicode_object(8, { 'r', 'e', 'a', 'd', 'i', 'n', 't', 'o'}) },
    .id_readinto1 = { unicode_object(9, { 'r', 'e', 'a', 'd', 'i', 'n', 't', 'o', '1'}) },
    .id_readline = { unicode_object(8, { 'r', 'e', 'a', 'd', 'l', 'i', 'n', 'e'}) },
    .id_reason = { unicode_object(6, { 'r', 'e', 'a', 's', 'o', 'n'}) },
    .id_reducer_override = { unicode_object(16, { 'r', 'e', 'd', 'u', 'c', 'e', 'r', '_', 'o', 'v', 'e', 'r', 'r', 'i', 'd', 'e'}) },
    .id_reload = { unicode_object(6, { 'r', 'e', 'l', 'o', 'a', 'd'}) },
    .id_replace = { unicode_object(7, { 'r', 'e', 'p', 'l', 'a', 'c', 'e'}) },
    .id_reset = { unicode_object(5, { 'r', 'e', 's', 'e', 't'}) },
    .id_return = { unicode_object(6, { 'r', 'e', 't', 'u', 'r', 'n'}) },
    .id_reversed = { unicode_object(8, { 'r', 'e', 'v', 'e', 'r', 's', 'e', 'd'}) },
    .id_seek = { unicode_object(4, { 's', 'e', 'e', 'k'}) },
    .id_seekable = { unicode_object(8, { 's', 'e', 'e', 'k', 'a', 'b', 'l', 'e'}) },
    .id_send = { unicode_object(4, { 's', 'e', 'n', 'd'}) },
    .id_setstate = { unicode_object(8, { 's', 'e', 't', 's', 't', 'a', 't', 'e'}) },
    .id_sort = { unicode_object(4, { 's', 'o', 'r', 't'}) },
    .id_source_traceback = { unicode_object(16, { 's', 'o', 'u', 'r', 'c', 'e', '_', 't', 'r', 'a', 'c', 'e', 'b', 'a', 'c', 'k'}) },
    .id_special = { unicode_object(7, { 's', 'p', 'e', 'c', 'i', 'a', 'l'}) },
    .id_start_offset = { unicode_object(12, { 's', 't', 'a', 'r', 't', '_', 'o', 'f', 'f', 's', 'e', 't'}) },
    .id_status = { unicode_object(6, { 's', 't', 'a', 't', 'u', 's'}) },
    .id_stderr = { unicode_object(6, { 's', 't', 'd', 'e', 'r', 'r'}) },
    .id_stdin = { unicode_object(5, { 's', 't', 'd', 'i', 'n'}) },
    .id_stdout = { unicode_object(6, { 's', 't', 'd', 'o', 'u', 't'}) },
    .id_strftime = { unicode_object(8, { 's', 't', 'r', 'f', 't', 'i', 'm', 'e'}) },
    .id_strict = { unicode_object(6, { 's', 't', 'r', 'i', 'c', 't'}) },
    .id_struct_time = { unicode_object(11, { 's', 't', 'r', 'u', 'c', 't', '_', 't', 'i', 'm', 'e'}) },
    .id_symmetric_difference_update = { unicode_object(27, { 's', 'y', 'm', 'm', 'e', 't', 'r', 'i', 'c', '_', 'd', 'i', 'f', 'f', 'e', 'r', 'e', 'n', 'c', 'e', '_', 'u', 'p', 'd', 'a', 't', 'e'}) },
    .id_tail = { unicode_object(4, { 't', 'a', 'i', 'l'}) },
    .id_task = { unicode_object(4, { 't', 'a', 's', 'k'}) },
    .id_tell = { unicode_object(4, { 't', 'e', 'l', 'l'}) },
    .id_test_unicode_id_init = { unicode_object(20, { 't', 'e', 's', 't', '_', 'u', 'n', 'i', 'c', 'o', 'd', 'e', '_', 'i', 'd', '_', 'i', 'n', 'i', 't'}) },
    .id_text = { unicode_object(4, { 't', 'e', 'x', 't'}) },
    .id_threading = { unicode_object(9, { 't', 'h', 'r', 'e', 'a', 'd', 'i', 'n', 'g'}) },
    .id_throw = { unicode_object(5, { 't', 'h', 'r', 'o', 'w'}) },
    .id_time = { unicode_object(4, { 't', 'i', 'm', 'e'}) },
    .id_timetuple = { unicode_object(9, { 't', 'i', 'm', 'e', 't', 'u', 'p', 'l', 'e'}) },
    .id_true = { unicode_object(4, { 't', 'r', 'u', 'e'}) },
    .id_tzname = { unicode_object(6, { 't', 'z', 'n', 'a', 'm', 'e'}) },
    .id_unraisablehook = { unicode_object(14, { 'u', 'n', 'r', 'a', 'i', 's', 'a', 'b', 'l', 'e', 'h', 'o', 'o', 'k'}) },
    .id_upper = { unicode_object(5, { 'u', 'p', 'p', 'e', 'r'}) },
    .id_values = { unicode_object(6, { 'v', 'a', 'l', 'u', 'e', 's'}) },
    .id_verify_code = { unicode_object(11, { 'v', 'e', 'r', 'i', 'f', 'y', '_', 'c', 'o', 'd', 'e'}) },
    .id_verify_message = { unicode_object(14, { 'v', 'e', 'r', 'i', 'f', 'y', '_', 'm', 'e', 's', 's', 'a', 'g', 'e'}) },
    .id_version = { unicode_object(7, { 'v', 'e', 'r', 's', 'i', 'o', 'n'}) },
    .id_warnings = { unicode_object(8, { 'w', 'a', 'r', 'n', 'i', 'n', 'g', 's'}) },
    .id_warnoptions = { unicode_object(11, { 'w', 'a', 'r', 'n', 'o', 'p', 't', 'i', 'o', 'n', 's'}) },
    .id_writable = { unicode_object(8, { 'w', 'r', 'i', 't', 'a', 'b', 'l', 'e'}) },
    .id_write = { unicode_object(5, { 'w', 'r', 'i', 't', 'e'}) },
    .id_zipimporter = { unicode_object(11, { 'z', 'i', 'p', 'i', 'm', 'p', 'o', 'r', 't', 'e', 'r'}) },
    .id_CANCELLED = { unicode_object(9, { 'C', 'A', 'N', 'C', 'E', 'L', 'L', 'E', 'D'}) },
    .id_COLS = { unicode_object(4, { 'C', 'O', 'L', 'S'}) },
    .id_FINISHED = { unicode_object(8, { 'F', 'I', 'N', 'I', 'S', 'H', 'E', 'D'}) },
    .id_JSONDecodeError = { unicode_object(15, { 'J', 'S', 'O', 'N', 'D', 'e', 'c', 'o', 'd', 'e', 'E', 'r', 'r', 'o', 'r'}) },
    .id_LINES = { unicode_object(5, { 'L', 'I', 'N', 'E', 'S'}) },
    .id_NFC = { unicode_object(3, { 'N', 'F', 'C'}) },
    .id_NFD = { unicode_object(3, { 'N', 'F', 'D'}) },
    .id_NFKC = { unicode_object(4, { 'N', 'F', 'K', 'C'}) },
    .id_NFKD = { unicode_object(4, { 'N', 'F', 'K', 'D'}) },
    .id_PENDING = { unicode_object(7, { 'P', 'E', 'N', 'D', 'I', 'N', 'G'}) },
    .id_Py_Repr = { unicode_object(7, { 'P', 'y', '_', 'R', 'e', 'p', 'r'}) },
    .id_TextIOWrapper = { unicode_object(13, { 'T', 'e', 'x', 't', 'I', 'O', 'W', 'r', 'a', 'p', 'p', 'e', 'r'}) },
    .id_WarningMessage = { unicode_object(14, { 'W', 'a', 'r', 'n', 'i', 'n', 'g', 'M', 'e', 's', 's', 'a', 'g', 'e'}) },
};



void _Py_intern_identifiers(void)
{
    PyObject *ref;
    init_unicode_object(__abc_tpflags__);
    init_unicode_object(__abs__);
    init_unicode_object(__abstractmethods__);
    init_unicode_object(__adapt__);
    init_unicode_object(__add__);
    init_unicode_object(__aenter__);
    init_unicode_object(__aexit__);
    init_unicode_object(__aiter__);
    init_unicode_object(__all__);
    init_unicode_object(__and__);
    init_unicode_object(__anext__);
    init_unicode_object(__annotations__);
    init_unicode_object(__args__);
    init_unicode_object(__asyncio_running_event_loop__);
    init_unicode_object(__await__);
    init_unicode_object(__bases__);
    init_unicode_object(__bool__);
    init_unicode_object(__build_class__);
    init_unicode_object(__builtins__);
    init_unicode_object(__bytes__);
    init_unicode_object(__call__);
    init_unicode_object(__cantrace__);
    init_unicode_object(__ceil__);
    init_unicode_object(__class__);
    init_unicode_object(__class_getitem__);
    init_unicode_object(__classcell__);
    init_unicode_object(__complex__);
    init_unicode_object(__conform__);
    init_unicode_object(__contains__);
    init_unicode_object(__copy__);
    init_unicode_object(__ctypes_from_outparam__);
    init_unicode_object(__del__);
    init_unicode_object(__delattr__);
    init_unicode_object(__delete__);
    init_unicode_object(__delitem__);
    init_unicode_object(__dict__);
    init_unicode_object(__dir__);
    init_unicode_object(__divmod__);
    init_unicode_object(__doc__);
    init_unicode_object(__enter__);
    init_unicode_object(__eq__);
    init_unicode_object(__exit__);
    init_unicode_object(__file__);
    init_unicode_object(__floor__);
    init_unicode_object(__floordiv__);
    init_unicode_object(__float__);
    init_unicode_object(__format__);
    init_unicode_object(__fspath__);
    init_unicode_object(__ge__);
    init_unicode_object(__get__);
    init_unicode_object(__getattr__);
    init_unicode_object(__getattribute__);
    init_unicode_object(__getinitargs__);
    init_unicode_object(__getitem__);
    init_unicode_object(__getnewargs__);
    init_unicode_object(__getnewargs_ex__);
    init_unicode_object(__getstate__);
    init_unicode_object(__gt__);
    init_unicode_object(__hash__);
    init_unicode_object(__iadd__);
    init_unicode_object(__iand__);
    init_unicode_object(__ifloordiv__);
    init_unicode_object(__ilshift__);
    init_unicode_object(__import__);
    init_unicode_object(__imatmul__);
    init_unicode_object(__imod__);
    init_unicode_object(__imul__);
    init_unicode_object(__index__);
    init_unicode_object(__init__);
    init_unicode_object(__init_subclass__);
    init_unicode_object(__instancecheck__);
    init_unicode_object(__int__);
    init_unicode_object(__invert__);
    init_unicode_object(__ior__);
    init_unicode_object(__ipow__);
    init_unicode_object(__irshift__);
    init_unicode_object(__isabstractmethod__);
    init_unicode_object(__isub__);
    init_unicode_object(__iter__);
    init_unicode_object(__itruediv__);
    init_unicode_object(__ixor__);
    init_unicode_object(__le__);
    init_unicode_object(__len__);
    init_unicode_object(__length_hint__);
    init_unicode_object(__loader__);
    init_unicode_object(__lshift__);
    init_unicode_object(__ltrace__);
    init_unicode_object(__lt__);
    init_unicode_object(__main__);
    init_unicode_object(__matmul__);
    init_unicode_object(__missing__);
    init_unicode_object(__mod__);
    init_unicode_object(__module__);
    init_unicode_object(__mro_entries__);
    init_unicode_object(__mul__);
    init_unicode_object(__name__);
    init_unicode_object(__ne__);
    init_unicode_object(__neg__);
    init_unicode_object(__new__);
    init_unicode_object(__newobj__);
    init_unicode_object(__newobj_ex__);
    init_unicode_object(__next__);
    init_unicode_object(__or__);
    init_unicode_object(__origin__);
    init_unicode_object(__package__);
    init_unicode_object(__parameters__);
    init_unicode_object(__path__);
    init_unicode_object(__pos__);
    init_unicode_object(__pow__);
    init_unicode_object(__prepare__);
    init_unicode_object(__qualname__);
    init_unicode_object(__radd__);
    init_unicode_object(__rand__);
    init_unicode_object(__rdivmod__);
    init_unicode_object(__reduce__);
    init_unicode_object(__reduce_ex__);
    init_unicode_object(__repr__);
    init_unicode_object(__reversed__);
    init_unicode_object(__rfloordiv__);
    init_unicode_object(__rlshift__);
    init_unicode_object(__rmatmul__);
    init_unicode_object(__rmod__);
    init_unicode_object(__rmul__);
    init_unicode_object(__ror__);
    init_unicode_object(__round__);
    init_unicode_object(__rpow__);
    init_unicode_object(__rrshift__);
    init_unicode_object(__rshift__);
    init_unicode_object(__rsub__);
    init_unicode_object(__rtruediv__);
    init_unicode_object(__rxor__);
    init_unicode_object(__set__);
    init_unicode_object(__set_name__);
    init_unicode_object(__setattr__);
    init_unicode_object(__setitem__);
    init_unicode_object(__setstate__);
    init_unicode_object(__sizeof__);
    init_unicode_object(__slotnames__);
    init_unicode_object(__slots__);
    init_unicode_object(__spec__);
    init_unicode_object(__str__);
    init_unicode_object(__sub__);
    init_unicode_object(__subclasscheck__);
    init_unicode_object(__subclasshook__);
    init_unicode_object(__tp_del__);
    init_unicode_object(__truediv__);
    init_unicode_object(__trunc__);
    init_unicode_object(__warningregistry__);
    init_unicode_object(__weakref__);
    init_unicode_object(__xor__);
    init_unicode_object(_);
    init_unicode_object(__IOBase_closed);
    init_unicode_object(_abc_impl);
    init_unicode_object(_abstract_);
    init_unicode_object(_anonymous_);
    init_unicode_object(_argtypes_);
    init_unicode_object(_array_reconstructor);
    init_unicode_object(_as_parameter_);
    init_unicode_object(_asyncio_future_blocking);
    init_unicode_object(_blksize);
    init_unicode_object(_check_retval_);
    init_unicode_object(_dealloc_warn);
    init_unicode_object(_fields_);
    init_unicode_object(_finalizing);
    init_unicode_object(_find_and_load);
    init_unicode_object(_fix_up_module);
    init_unicode_object(_flags_);
    init_unicode_object(_get_sourcefile);
    init_unicode_object(_handle_fromlist);
    init_unicode_object(_initializing);
    init_unicode_object(_is_text_encoding);
    init_unicode_object(_iterdump);
    init_unicode_object(_length_);
    init_unicode_object(_lock_unlock_module);
    init_unicode_object(_loop);
    init_unicode_object(_needs_com_addref_);
    init_unicode_object(_pack_);
    init_unicode_object(_repr_info);
    init_unicode_object(_restype_);
    init_unicode_object(_showwarnmsg);
    init_unicode_object(_shutdown);
    init_unicode_object(_slotnames);
    init_unicode_object(_strptime_datetime);
    init_unicode_object(_strptime_time);
    init_unicode_object(_swappedbytes_);
    init_unicode_object(_type_);
    init_unicode_object(_uninitialized_submodules);
    init_unicode_object(_use_broken_old_ctypes_structure_semantics_);
    init_unicode_object(_warn_unawaited_coroutine);
    init_unicode_object(_xoptions);
    init_unicode_object(add);
    init_unicode_object(add_done_callback);
    init_unicode_object(append);
    init_unicode_object(as_integer_ratio);
    init_unicode_object(big);
    init_unicode_object(buffer);
    init_unicode_object(builtins);
    init_unicode_object(call_exception_handler);
    init_unicode_object(call_soon);
    init_unicode_object(cancel);
    init_unicode_object(clear);
    init_unicode_object(close);
    init_unicode_object(code);
    init_unicode_object(copy);
    init_unicode_object(copyreg);
    init_unicode_object(cursor);
    init_unicode_object(decode);
    init_unicode_object(default);
    init_unicode_object(defaultaction);
    init_unicode_object(dict_size);
    init_unicode_object(difference_update);
    init_unicode_object(discard);
    init_unicode_object(dispatch_table);
    init_unicode_object(displayhook);
    init_unicode_object(dist);
    init_unicode_object(doctype);
    init_unicode_object(enable);
    init_unicode_object(encoding);
    init_unicode_object(end_lineno);
    init_unicode_object(end_offset);
    init_unicode_object(errors);
    init_unicode_object(excepthook);
    init_unicode_object(exception);
    init_unicode_object(execute);
    init_unicode_object(executemany);
    init_unicode_object(executescript);
    init_unicode_object(extend);
    init_unicode_object(false);
    init_unicode_object(filename);
    init_unicode_object(fileno);
    init_unicode_object(fillvalue);
    init_unicode_object(filters);
    init_unicode_object(finalize);
    init_unicode_object(find);
    init_unicode_object(find_class);
    init_unicode_object(findall);
    init_unicode_object(findtext);
    init_unicode_object(flush);
    init_unicode_object(foo);
    init_unicode_object(from_param);
    init_unicode_object(fromtimestamp);
    init_unicode_object(fromutc);
    init_unicode_object(future);
    init_unicode_object(get);
    init_unicode_object(get_debug);
    init_unicode_object(get_event_loop);
    init_unicode_object(get_loop);
    init_unicode_object(get_source);
    init_unicode_object(getattr);
    init_unicode_object(getnextcabinet);
    init_unicode_object(id);
    init_unicode_object(ignore);
    init_unicode_object(importlib);
    init_unicode_object(insert);
    init_unicode_object(intersection);
    init_unicode_object(isatty);
    init_unicode_object(isoformat);
    init_unicode_object(items);
    init_unicode_object(iter);
    init_unicode_object(iterfind);
    init_unicode_object(keys);
    init_unicode_object(last_traceback);
    init_unicode_object(last_type);
    init_unicode_object(last_value);
    init_unicode_object(latin1);
    init_unicode_object(lc);
    init_unicode_object(lp);
    init_unicode_object(library);
    init_unicode_object(lineno);
    init_unicode_object(little);
    init_unicode_object(match);
    init_unicode_object(message);
    init_unicode_object(metaclass);
    init_unicode_object(mode);
    init_unicode_object(modules);
    init_unicode_object(mro);
    init_unicode_object(msg);
    init_unicode_object(n_fields);
    init_unicode_object(n_sequence_fields);
    init_unicode_object(n_unnamed_fields);
    init_unicode_object(name);
    init_unicode_object(null);
    init_unicode_object(obj);
    init_unicode_object(offset);
    init_unicode_object(onceregistry);
    init_unicode_object(open);
    init_unicode_object(parent);
    init_unicode_object(partial);
    init_unicode_object(path);
    init_unicode_object(pb);
    init_unicode_object(peek);
    init_unicode_object(persistent_id);
    init_unicode_object(persistent_load);
    init_unicode_object(print_file_and_line);
    init_unicode_object(ps1);
    init_unicode_object(ps2);
    init_unicode_object(raw);
    init_unicode_object(read);
    init_unicode_object(read1);
    init_unicode_object(readable);
    init_unicode_object(readall);
    init_unicode_object(readinto);
    init_unicode_object(readinto1);
    init_unicode_object(readline);
    init_unicode_object(reason);
    init_unicode_object(reducer_override);
    init_unicode_object(reload);
    init_unicode_object(replace);
    init_unicode_object(reset);
    init_unicode_object(return);
    init_unicode_object(reversed);
    init_unicode_object(seek);
    init_unicode_object(seekable);
    init_unicode_object(send);
    init_unicode_object(setstate);
    init_unicode_object(sort);
    init_unicode_object(source_traceback);
    init_unicode_object(special);
    init_unicode_object(start_offset);
    init_unicode_object(status);
    init_unicode_object(stderr);
    init_unicode_object(stdin);
    init_unicode_object(stdout);
    init_unicode_object(strftime);
    init_unicode_object(strict);
    init_unicode_object(struct_time);
    init_unicode_object(symmetric_difference_update);
    init_unicode_object(tail);
    init_unicode_object(task);
    init_unicode_object(tell);
    init_unicode_object(test_unicode_id_init);
    init_unicode_object(text);
    init_unicode_object(threading);
    init_unicode_object(throw);
    init_unicode_object(time);
    init_unicode_object(timetuple);
    init_unicode_object(true);
    init_unicode_object(tzname);
    init_unicode_object(unraisablehook);
    init_unicode_object(upper);
    init_unicode_object(values);
    init_unicode_object(verify_code);
    init_unicode_object(verify_message);
    init_unicode_object(version);
    init_unicode_object(warnings);
    init_unicode_object(warnoptions);
    init_unicode_object(writable);
    init_unicode_object(write);
    init_unicode_object(zipimporter);
    init_unicode_object(CANCELLED);
    init_unicode_object(COLS);
    init_unicode_object(FINISHED);
    init_unicode_object(JSONDecodeError);
    init_unicode_object(LINES);
    init_unicode_object(NFC);
    init_unicode_object(NFD);
    init_unicode_object(NFKC);
    init_unicode_object(NFKD);
    init_unicode_object(PENDING);
    init_unicode_object(Py_Repr);
    init_unicode_object(TextIOWrapper);
    init_unicode_object(WarningMessage);
}
